name: cacheFlx
on:
  workflow_dispatch:
  
jobs:
  build:
    name: cacheFlx
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
          
      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hmm
          haxelib run hmm install
          
      - name: Save Haxelib cache
        uses: actions/cache/save@v4
        id: HaxelibCache
        with:
          key: cache-install-Haxelib
          path: |
            .haxelib/

      - name: Save androidbuild cache
        uses: actions/cache/save@v4
        id: AndroidCache
        with:
          key: cache-build-Android
          path: |
            .haxelib/
            
      - name: Save iOSbuild cache
        uses: actions/cache/save@v4
        id: iOSCache
        with:
          key: cache-build-iOS
          path: |
            .haxelib/