name: DesktopBuild
on: 
  workflow_dispatch:

  workflow_call:
    inputs:
      backup:
        required: false
        default: true
        type: boolean
jobs:
  installHaxelib:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event_name == 'pull_request'}}
    uses: ./.github/workflows/InstallHaxelib.yml
     
  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Install Libraries
        run: |
          haxelib setup C:\haxelib
          haxelib install hmm --quiet
          haxelib run hmm install --quiet

      - name: Compile
        run: haxelib run lime build windows

      - name: Make zip for release
        shell: pwsh
        run: | 
          cd export\release\windows\bin
          Compress-Archive -Path . -DestinationPath windows.zip

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild
          path: export\release\windows\bin\*.zip
          if-no-files-found: error
          
  LinuxBuild:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Installing LibVLC
        run: |
          sudo apt-get install libvlc-dev libvlccore-dev
          
      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hmm
          haxelib run hmm install
          
      - name: Compile
        run: |
          haxelib run lime build linux
      
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: LinuxBuild
          path: export/release/linux/bin/
          
  macOS:
    runs-on: macos-${{matrix.version}}
    strategy:
      matrix:
        version: [14, 15]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hmm --quiet
          haxelib run hmm install --quiet

      - name: Compile
        run: haxelib run lime build mac

      - name: Make tar for relese
        run: |
          cd export/release/macos/bin
          tar czf macOS${{matrix.version}}.tar .

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: macOSBuild-${{matrix.version}}
          path: export/release/macos/bin/*.tar
          if-no-files-found: error

