name: InstallHaxelib

on:
  workflow_dispatch:
  workflow_call:

env:
  HAXE_VERSION: 4.3.6

jobs:
  build:
    name: InstallHaxelib
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}
        
      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hmm 
          haxelib run hmm install

      - name: Make Haxelib Zip
        run: |
          zip -r /Users/runner/haxelib.zip .haxelib/

      - name: Upload Haxelib
        uses: actions/upload-artifact@main
        with:
          name: Haxelib
          path: /Users/runner/haxelib.zip
          if-no-files-found: error
